name: release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    strategy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Build
        run: .github/workflows/build_release.sh

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./aws-in-a-box-*
